name: Deployment

on:
  push:
    branches:
    - main

  workflow_dispatch:
  
jobs:
  deploy:
  
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    steps:
    
      - id: 'checkout'
        uses: actions/checkout@v2

      - id: 'app-yml'
        env:
          DOT_ENV: ${{ secrets.ENV }}
        run: |
          chmod +x ./scripts/create-app-yml.sh
          ./scripts/create-app-yml.sh "$(echo $DOT_ENV | base64 --decode)"

        shell: bash
        
      - id: 'deployment'
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: glasshouse-341514
          version: master
          credentials: ${{secrets.GOOGLE_APP_ENGINE_KEY}}
          flags: --no-cache
          deliverables: app.yaml
          
      - id: 'test'
        run: 'curl "${{ steps.deployment.outputs.url }}"'

      - id: 'heroku-env'
        env:
          HEROKU_ENV: ${{ secrets.HEROKU_ENV }}
        run: echo $DOT_ENV | base64 --decode > .env

      - id: 'heroku'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          env_file: ".env"
