name: Deployment

on:
  push:
    branches:
    - main

  workflow_dispatch:
  
jobs:
  deploy:
  
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    steps:
      - id: 'app-yml'
        env:
          DOT_ENV: ${{ secrets.ENV }}
        run : |
          chmod +x create-app-yml.sh
          ./create-app-yml.sh "$($DOT_ENV | base64 --decode)"
    
      - id: 'checkout'
        uses: actions/checkout@v2
        
      - id: 'deployment'
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: glasshouse-341514
          version: master
          credentials: ${{secrets.GOOGLE_APP_ENGINE_KEY}}
          flags: --no-cache
          deliverables: app.yaml
          
      - id: 'test'
        run: 'curl "${{ steps.deployment.outputs.url }}"'
